UPDATE workflow and Conf: VP_SUBSCRIBE_DATA_FILE, VP_SUBSCRIBE_URL Support yaml

diff --git a/.github/workflows/release_tag.yml b/.github/workflows/release_tag.yml
--- a/.github/workflows/release_tag.yml
+++ b/.github/workflows/release_tag.yml
@@ -79,10 +79,11 @@ jobs:
         if: matrix.goos == 'windows'
         run: |
           go install github.com/josephspurrier/goversioninfo/cmd/goversioninfo@latest
-          go env GOPATH
-          ls `go env GOPATH`/bin
-          go generate ./main || echo "try export PATH ..." && export PATH=$PATH:`go env GOPATH`/bin && go generate ./main
-
+          GOPATH=$(go env GOPATH)
+          GOVERSIONINFO_TOOL="$GOPATH/bin/goversioninfo"
+          ls $GOPATH $GOVERSIONINFO_TOOL
+          cd main && $GOVERSIONINFO_TOOL versioninfo.json && cd .. && ls main/resource.syso || echo "generate resource.syso fail"
+    
       - name: Build
         run: |
           echo 'hello.ref=${{ github.ref }}'
